const SET_LOCATION_PERMISSION = 'SET_LOCATION_PERMISSION';
const SET_LOCATION = 'SET_LOCATION';

const SET_USER = 'SET_USER';
const REMOVE_USER = 'REMOVE_USER';
const SET_AVATAR = 'SET_AVATAR';
const ALTER_USER = 'ALTER_USER';

const SET_PAYTM = 'SET_PAYTM';
const REMOVE_PAYTM = 'REMOVE_PAYTM';

const SET_METHOD = 'SET_METHOD';
const REMOVE_METHOD = 'REMOVE_METHOD';

export {
    SET_LOCATION_PERMISSION,
    SET_LOCATION,
    SET_USER,
    REMOVE_USER,
    SET_AVATAR,
    ALTER_USER,
    SET_METHOD,
    REMOVE_METHOD,
    SET_PAYTM,
    REMOVE_PAYTM
};
